/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import persistencia.tables.Palabrassubfijosprefijos;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PalabrassubfijosprefijosRecord extends UpdatableRecordImpl<PalabrassubfijosprefijosRecord> implements Record3<Integer, String, Integer> {

	private static final long serialVersionUID = -1500204386;

	/**
	 * Setter for <code>kutipak.palabrassubfijosprefijos.ID</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.palabrassubfijosprefijos.ID</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.palabrassubfijosprefijos.PALABRA</code>.
	 */
	public void setPalabra(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.palabrassubfijosprefijos.PALABRA</code>.
	 */
	public String getPalabra() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>kutipak.palabrassubfijosprefijos.IDIOMA</code>.
	 */
	public void setIdioma(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>kutipak.palabrassubfijosprefijos.IDIOMA</code>.
	 */
	public Integer getIdioma() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Palabrassubfijosprefijos.PALABRASSUBFIJOSPREFIJOS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Palabrassubfijosprefijos.PALABRASSUBFIJOSPREFIJOS.PALABRA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Palabrassubfijosprefijos.PALABRASSUBFIJOSPREFIJOS.IDIOMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getPalabra();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getIdioma();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrassubfijosprefijosRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrassubfijosprefijosRecord value2(String value) {
		setPalabra(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrassubfijosprefijosRecord value3(Integer value) {
		setIdioma(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrassubfijosprefijosRecord values(Integer value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PalabrassubfijosprefijosRecord
	 */
	public PalabrassubfijosprefijosRecord() {
		super(Palabrassubfijosprefijos.PALABRASSUBFIJOSPREFIJOS);
	}

	/**
	 * Create a detached, initialised PalabrassubfijosprefijosRecord
	 */
	public PalabrassubfijosprefijosRecord(Integer id, String palabra, Integer idioma) {
		super(Palabrassubfijosprefijos.PALABRASSUBFIJOSPREFIJOS);

		setValue(0, id);
		setValue(1, palabra);
		setValue(2, idioma);
	}
}
