/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;

import persistencia.tables.Pantallapalabras;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PantallapalabrasRecord extends TableRecordImpl<PantallapalabrasRecord> implements Record8<Integer, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = 629199467;

	/**
	 * Setter for <code>kutipak.pantallapalabras.palabraid</code>.
	 */
	public void setPalabraid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.palabraid</code>.
	 */
	public Integer getPalabraid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.IDIOMA</code>.
	 */
	public void setIdioma(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.IDIOMA</code>.
	 */
	public String getIdioma() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.PALABRAS</code>.
	 */
	public void setPalabras(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.PALABRAS</code>.
	 */
	public String getPalabras() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.SIGNIFICADO</code>.
	 */
	public void setSignificado(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.SIGNIFICADO</code>.
	 */
	public String getSignificado() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.TIPO</code>.
	 */
	public void setTipo(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.TIPO</code>.
	 */
	public String getTipo() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.NOMBRETIPO</code>.
	 */
	public void setNombretipo(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.NOMBRETIPO</code>.
	 */
	public String getNombretipo() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.NOMBRETIEMPO</code>.
	 */
	public void setNombretiempo(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.NOMBRETIEMPO</code>.
	 */
	public String getNombretiempo() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.TIEMPO</code>.
	 */
	public void setTiempo(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.TIEMPO</code>.
	 */
	public String getTiempo() {
		return (String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, String, String, String, String, String, String> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, String, String, String, String, String, String> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Pantallapalabras.PANTALLAPALABRAS.PALABRAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Pantallapalabras.PANTALLAPALABRAS.IDIOMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Pantallapalabras.PANTALLAPALABRAS.PALABRAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Pantallapalabras.PANTALLAPALABRAS.SIGNIFICADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Pantallapalabras.PANTALLAPALABRAS.TIPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Pantallapalabras.PANTALLAPALABRAS.NOMBRETIPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Pantallapalabras.PANTALLAPALABRAS.NOMBRETIEMPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Pantallapalabras.PANTALLAPALABRAS.TIEMPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPalabraid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getIdioma();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPalabras();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getSignificado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getTipo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getNombretipo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getNombretiempo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getTiempo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value1(Integer value) {
		setPalabraid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value2(String value) {
		setIdioma(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value3(String value) {
		setPalabras(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value4(String value) {
		setSignificado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value5(String value) {
		setTipo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value6(String value) {
		setNombretipo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value7(String value) {
		setNombretiempo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value8(String value) {
		setTiempo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PantallapalabrasRecord
	 */
	public PantallapalabrasRecord() {
		super(Pantallapalabras.PANTALLAPALABRAS);
	}

	/**
	 * Create a detached, initialised PantallapalabrasRecord
	 */
	public PantallapalabrasRecord(Integer palabraid, String idioma, String palabras, String significado, String tipo, String nombretipo, String nombretiempo, String tiempo) {
		super(Pantallapalabras.PANTALLAPALABRAS);

		setValue(0, palabraid);
		setValue(1, idioma);
		setValue(2, palabras);
		setValue(3, significado);
		setValue(4, tipo);
		setValue(5, nombretipo);
		setValue(6, nombretiempo);
		setValue(7, tiempo);
	}
}
