/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import persistencia.tables.Sugerencias;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SugerenciasRecord extends UpdatableRecordImpl<SugerenciasRecord> implements Record5<Integer, Boolean, Boolean, String, Timestamp> {

	private static final long serialVersionUID = 1927957710;

	/**
	 * Setter for <code>kutipak.sugerencias.sugerenciasID</code>.
	 */
	public void setSugerenciasid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.sugerencias.sugerenciasID</code>.
	 */
	public Integer getSugerenciasid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.sugerencias.sirvio</code>.
	 */
	public void setSirvio(Boolean value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.sugerencias.sirvio</code>.
	 */
	public Boolean getSirvio() {
		return (Boolean) getValue(1);
	}

	/**
	 * Setter for <code>kutipak.sugerencias.tiempo</code>.
	 */
	public void setTiempo(Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>kutipak.sugerencias.tiempo</code>.
	 */
	public Boolean getTiempo() {
		return (Boolean) getValue(2);
	}

	/**
	 * Setter for <code>kutipak.sugerencias.comentario</code>.
	 */
	public void setComentario(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>kutipak.sugerencias.comentario</code>.
	 */
	public String getComentario() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>kutipak.sugerencias.fecha</code>.
	 */
	public void setFecha(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>kutipak.sugerencias.fecha</code>.
	 */
	public Timestamp getFecha() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Boolean, Boolean, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Boolean, Boolean, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Sugerencias.SUGERENCIAS.SUGERENCIASID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field2() {
		return Sugerencias.SUGERENCIAS.SIRVIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field3() {
		return Sugerencias.SUGERENCIAS.TIEMPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Sugerencias.SUGERENCIAS.COMENTARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Sugerencias.SUGERENCIAS.FECHA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getSugerenciasid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value2() {
		return getSirvio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value3() {
		return getTiempo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getComentario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getFecha();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SugerenciasRecord value1(Integer value) {
		setSugerenciasid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SugerenciasRecord value2(Boolean value) {
		setSirvio(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SugerenciasRecord value3(Boolean value) {
		setTiempo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SugerenciasRecord value4(String value) {
		setComentario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SugerenciasRecord value5(Timestamp value) {
		setFecha(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SugerenciasRecord values(Integer value1, Boolean value2, Boolean value3, String value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SugerenciasRecord
	 */
	public SugerenciasRecord() {
		super(Sugerencias.SUGERENCIAS);
	}

	/**
	 * Create a detached, initialised SugerenciasRecord
	 */
	public SugerenciasRecord(Integer sugerenciasid, Boolean sirvio, Boolean tiempo, String comentario, Timestamp fecha) {
		super(Sugerencias.SUGERENCIAS);

		setValue(0, sugerenciasid);
		setValue(1, sirvio);
		setValue(2, tiempo);
		setValue(3, comentario);
		setValue(4, fecha);
	}
}
