/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contador implements Serializable {

	private static final long serialVersionUID = -200729851;

	private Integer contadorid;
	private Integer valor;

	public Contador() {}

	public Contador(Contador value) {
		this.contadorid = value.contadorid;
		this.valor = value.valor;
	}

	public Contador(
		Integer contadorid,
		Integer valor
	) {
		this.contadorid = contadorid;
		this.valor = valor;
	}

	public Integer getContadorid() {
		return this.contadorid;
	}

	public void setContadorid(Integer contadorid) {
		this.contadorid = contadorid;
	}

	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}
}
