/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contador implements Serializable {

	private static final long serialVersionUID = 1478767818;

	private Integer   contadorid;
	private Integer   valor;
	private Timestamp fecha;

	public Contador() {}

	public Contador(Contador value) {
		this.contadorid = value.contadorid;
		this.valor = value.valor;
		this.fecha = value.fecha;
	}

	public Contador(
		Integer   contadorid,
		Integer   valor,
		Timestamp fecha
	) {
		this.contadorid = contadorid;
		this.valor = valor;
		this.fecha = fecha;
	}

	public Integer getContadorid() {
		return this.contadorid;
	}

	public void setContadorid(Integer contadorid) {
		this.contadorid = contadorid;
	}

	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}
}
