/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Palabrassubfijosprefijos implements Serializable {

	private static final long serialVersionUID = 1696444003;

	private Integer id;
	private String  palabra;
	private Integer idioma;

	public Palabrassubfijosprefijos() {}

	public Palabrassubfijosprefijos(Palabrassubfijosprefijos value) {
		this.id = value.id;
		this.palabra = value.palabra;
		this.idioma = value.idioma;
	}

	public Palabrassubfijosprefijos(
		Integer id,
		String  palabra,
		Integer idioma
	) {
		this.id = id;
		this.palabra = palabra;
		this.idioma = idioma;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPalabra() {
		return this.palabra;
	}

	public void setPalabra(String palabra) {
		this.palabra = palabra;
	}

	public Integer getIdioma() {
		return this.idioma;
	}

	public void setIdioma(Integer idioma) {
		this.idioma = idioma;
	}
}
