/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Palabras implements Serializable {

	private static final long serialVersionUID = 1729146616;

	private Integer palabraid;
	private Integer idiomaid;
	private Integer tipoid;
	private Integer tiemposid;
	private String  nombrepalabra;
	private String  sinonimo;
	private String  significado;

	public Palabras() {}

	public Palabras(Palabras value) {
		this.palabraid = value.palabraid;
		this.idiomaid = value.idiomaid;
		this.tipoid = value.tipoid;
		this.tiemposid = value.tiemposid;
		this.nombrepalabra = value.nombrepalabra;
		this.sinonimo = value.sinonimo;
		this.significado = value.significado;
	}

	public Palabras(
		Integer palabraid,
		Integer idiomaid,
		Integer tipoid,
		Integer tiemposid,
		String  nombrepalabra,
		String  sinonimo,
		String  significado
	) {
		this.palabraid = palabraid;
		this.idiomaid = idiomaid;
		this.tipoid = tipoid;
		this.tiemposid = tiemposid;
		this.nombrepalabra = nombrepalabra;
		this.sinonimo = sinonimo;
		this.significado = significado;
	}

	public Integer getPalabraid() {
		return this.palabraid;
	}

	public void setPalabraid(Integer palabraid) {
		this.palabraid = palabraid;
	}

	public Integer getIdiomaid() {
		return this.idiomaid;
	}

	public void setIdiomaid(Integer idiomaid) {
		this.idiomaid = idiomaid;
	}

	public Integer getTipoid() {
		return this.tipoid;
	}

	public void setTipoid(Integer tipoid) {
		this.tipoid = tipoid;
	}

	public Integer getTiemposid() {
		return this.tiemposid;
	}

	public void setTiemposid(Integer tiemposid) {
		this.tiemposid = tiemposid;
	}

	public String getNombrepalabra() {
		return this.nombrepalabra;
	}

	public void setNombrepalabra(String nombrepalabra) {
		this.nombrepalabra = nombrepalabra;
	}

	public String getSinonimo() {
		return this.sinonimo;
	}

	public void setSinonimo(String sinonimo) {
		this.sinonimo = sinonimo;
	}

	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}
}
