/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sugerencias implements Serializable {

	private static final long serialVersionUID = 1867954836;

	private Integer sugerenciasid;
	private Boolean sirvio;
	private Boolean tiempo;
	private String  comentario;

	public Sugerencias() {}

	public Sugerencias(Sugerencias value) {
		this.sugerenciasid = value.sugerenciasid;
		this.sirvio = value.sirvio;
		this.tiempo = value.tiempo;
		this.comentario = value.comentario;
	}

	public Sugerencias(
		Integer sugerenciasid,
		Boolean sirvio,
		Boolean tiempo,
		String  comentario
	) {
		this.sugerenciasid = sugerenciasid;
		this.sirvio = sirvio;
		this.tiempo = tiempo;
		this.comentario = comentario;
	}

	public Integer getSugerenciasid() {
		return this.sugerenciasid;
	}

	public void setSugerenciasid(Integer sugerenciasid) {
		this.sugerenciasid = sugerenciasid;
	}

	public Boolean getSirvio() {
		return this.sirvio;
	}

	public void setSirvio(Boolean sirvio) {
		this.sirvio = sirvio;
	}

	public Boolean getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(Boolean tiempo) {
		this.tiempo = tiempo;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}
}
