/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tipospalabras implements Serializable {

	private static final long serialVersionUID = 1162333038;

	private Integer tipoid;
	private String  nombretipo;
	private String  nemotecnico;
	private String  codigoktpak;

	public Tipospalabras() {}

	public Tipospalabras(Tipospalabras value) {
		this.tipoid = value.tipoid;
		this.nombretipo = value.nombretipo;
		this.nemotecnico = value.nemotecnico;
		this.codigoktpak = value.codigoktpak;
	}

	public Tipospalabras(
		Integer tipoid,
		String  nombretipo,
		String  nemotecnico,
		String  codigoktpak
	) {
		this.tipoid = tipoid;
		this.nombretipo = nombretipo;
		this.nemotecnico = nemotecnico;
		this.codigoktpak = codigoktpak;
	}

	public Integer getTipoid() {
		return this.tipoid;
	}

	public void setTipoid(Integer tipoid) {
		this.tipoid = tipoid;
	}

	public String getNombretipo() {
		return this.nombretipo;
	}

	public void setNombretipo(String nombretipo) {
		this.nombretipo = nombretipo;
	}

	public String getNemotecnico() {
		return this.nemotecnico;
	}

	public void setNemotecnico(String nemotecnico) {
		this.nemotecnico = nemotecnico;
	}

	public String getCodigoktpak() {
		return this.codigoktpak;
	}

	public void setCodigoktpak(String codigoktpak) {
		this.codigoktpak = codigoktpak;
	}
}
